# action.yml
name: 'Count Lines of Code (tokei)'
description: 'Count Lines of Code with https://github.com/XAMPPRocky/tokei'

runs:
  using: 'docker'
  image: 'Dockerfile'

branding:
  icon: 'code'
  color: 'blue'
